Cast lo_server_thread to lo_server when calling liblo functions
The `lo_server_thread` struct extends `lo_server`, so it is safe to pass
one in place of the other. However, GCC does not know this and will
raise warnings unless we explicitly cast.

Fixes warnings such as this which get treated as errors by default:

    ../src/monomeserial.c: In function ‘register_osc_methods’:
    ../src/monomeserial.c:136:32: error: initialization of ‘lo_server_thread’ {aka ‘struct lo_server_thread_ *’} from incompatible pointer type ‘lo_server’ {aka ‘struct lo_server_ *’} [-Werror=incompatible-pointer-types]
      136 |         lo_server_thread srv = state.server;
          |                                ^~~~~
    ../src/monomeserial.c:140:30: error: passing argument 1 of ‘lo_server_add_method’ from incompatible pointer type [-Werror=incompatible-pointer-types]
      140 |         lo_server_add_method(srv, cmd_buf, "iii", osc_led_handler, monome);
          |                              ^~~
          |                              |
          |                              lo_server_thread {aka struct lo_server_thread_ *}