Use correct type for state.server and state.outgoing
The liblo types `lo_server` and `lo_address` are already pointer types.

Fixes various "incompatible pointer type" compile warnings, which are
treated as errors in the default build config:

    In file included from /app/include/lo/lo.h:264,
                     from ../src/monomeserial.c:27:
    ../src/monomeserial.c: In function ‘monome_handle_press’:
    ../src/monomeserial.c:210:27: error: passing argument 1 of ‘lo_send_from_internal’ from incompatible pointer type [-Werror=incompatible-pointer-types]
      210 |         lo_send_from(state.outgoing, (lo_server)state.server, LO_TT_IMMEDIATE, cmd, "iii",
          |                      ~~~~~^~~~~~~~~
          |                           |
          |                           struct lo_address_ **
    In file included from /app/include/lo/lo.h:32,
                     from ../src/monomeserial.c:27:
    /app/include/lo/lo_lowlevel.h:1091:38: note: expected ‘lo_address’ {aka ‘struct lo_address_ *’} but argument is of type ‘struct lo_address_ **’
     1091 | int lo_send_from_internal(lo_address targ, lo_server from, const char *file,
          |                           ~~~~~~~~~~~^~~~